### ISSUE TITLE
Garage App: Integrate Web3Modal for wallet connection

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#187]

**Comment by datadanne** [comment]
Do we have a strong preference for using Web3Modal? I've used [RainbowKit](https://www.rainbowkit.com) for my recent projects and I really like it so I'd go with that if it was up to me

**Comment by sanderpick** [comment]
Oh yeah, I haven't used that one, but I like the way it looks. Sounds good to me.
