### ISSUE TITLE
Garage App: Create CI/CD deploy flow

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#200]

**Comment by joewagner** [comment]
@sanderpick Do we know where we want the garage app to be hosted?

**Comment by sanderpick** [comment]
for the main app, we can use github pages and point it to `garage.tableland.xyz`.
for the `animation_url` app, we could use `rig.tableland.xyz/[rigId]`. we could explore using IPFS too, but sounds like a more cumbersome deploy.

since we'll need multiple pages, we'll have to use vercel or netlify. i've used netlify for this before, worked great, but vercel seems like what people are choosing now days.
