### ISSUE TITLE
Garage App: Create piloting flow with modal

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#201]
Since you can pilot a rig from the dash or from the rig page, a modal type flow sounds nice.

From the dash:
- you can select one or more rigs
- once a rig is selected, a pilot button appears
- clicking the pilot button opens a modal that let's you select a pilot for each selected rig
- if the rig hasn't been piloted before, the only option will be the trainer pilot
- click confirm which kicks of a transaction 
- we can show a spinner / loader while txn is pending and an error / success message when finalized

alternatively, if much easier, the "select" button as shown in the figma could just be "pilot/park", but you wouldn't be able to pilot multiple rigs in one transaction (which sounds useful for people w/ many rigs).

From rig page:
- same as above, but without the ability to pilot multiple rigs in one txn

In the future:
- when we have badges, we can add an additional step to the modal flow that lets the user configure which badges they want to display on the rig

**Comment by sanderpick** [comment]
@datadanne I added a little description of how I think this could work. this flow would contains the bulk of the user interactions in the garage. let me know if it's worth mocking up in figma.

**Comment by datadanne** [comment]
@dtbuchholz what do you think about the bulk piloting feature, is that something that we can and will support in the contract? There is no way to guarantee that a batch pilot tx doesn't run out of gas, we can always limit it so that we only support _n_ pilots per tx but even then it could fail if the user is trying to pilot a token from a contract with a bad `ownerOf` implementation that consumes too much gas. Probably pretty unlikely but you never know

**Comment by dtbuchholz** [comment]
@datadanne I can try testing out a bulk scenario vs solo Rig and see if there's a reasonable upper limit to impose. Or, for simplicity sake, we could always opt for the one Rig approach and make the bulk update a later feature.

**Comment by datadanne** [comment]
> @datadanne I can try testing out a bulk scenario vs solo Rig and see if there's a reasonable upper limit to impose. Or, for simplicity sake, we could always opt for the one Rig approach and make the bulk update a later feature.

SGTM! I'll start by implementing the one rig flow on the rig details page

**Comment by dtbuchholz** [comment]
Cool, sgtm, too.

**Comment by sanderpick** [comment]
Yep, I was thinking the contract could take a list of contract addresses and a list of token IDs. We could limit the length of those lists in the client? Say 5 or so?

**Comment by dtbuchholz** [comment]
Cool, I'll add that...maybe try it out first with some function overloading.
