### ISSUE TITLE
Rig App: Create basic app framework that can be viewed standalone via animation_url

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#203]
Sounds like we're going with svelte on this one since it compiles very small

**Comment by joewagner** [comment]
Basic framework with mock badge data is  here: https://github.com/tablelandnetwork/rigs/tree/joe/animation_url/animation_url

**Comment by joewagner** [comment]
@sanderpick I have the design in a good spot, how should we iterate/approve it? 


![Image](https://user-images.githubusercontent.com/1500995/192898163-9ba60239-40cb-42c6-add2-49a421fe9030.png)

**Comment by sanderpick** [comment]
Looks good! For the badges that layer over the rig, we have these svg icons: https://www.dropbox.com/sh/m6c3sk35rfdimci/AAC7Sf3viv8mnMZgDD4IMKjQa?dl=0.

We won't be adding the badges for a bit, but great that you have them in the layout already.

**Comment by joewagner** [comment]
Oh nice!  I was thinking the images in figma were the badges, I'll swap those out now.

**Comment by sanderpick** [comment]
There's two styles, the "icon" style and then the full "image" style. The icon ones were designed to be used over the rigs without adding too much noise / new colors 

<img width="329" alt="Screen Shot 2022-09-28 at 3 49 39 PM" src="https://user-images.githubusercontent.com/361000/192902189-604d2c20-f592-4e54-b257-6a5e503392b5.png">

<img width="215" alt="Screen Shot 2022-09-28 at 3 49 32 PM" src="https://user-images.githubusercontent.com/361000/192902207-e5f04f24-f471-41bd-96e5-ca5865e76d58.png">

**Comment by joewagner** [comment]
The latest is deployed to ipfs: https://tableland.mypinata.cloud/ipfs/QmVjgFNPDJQeeLTcooLXqCZcLhhKQcj7zSrepdgAUhxYyH?rig=1
The pilot and badges are still hard coded fake data

**Comment by sanderpick** [comment]
@joewagner what do you think about PRing this to `main`? ie, https://github.com/tablelandnetwork/rigs/compare/joe/animation_url?expand=1

**Comment by joewagner** [comment]
Sounds good to me, but when I run the svelte app it looks like the wrong rig is showing.  Are the queries for the rig going to a test table or something?

**Comment by joewagner** [comment]
Rig 5 shows https://nftstorage.link/ipfs/bafybeiaiqhz5n4475fbwl7ja6hppjbpnhynwxf23vqfcsqalbkvxcmf47u/5/image_medium.png
but rig 5 is an airelight
https://opensea.io/assets/ethereum/0x8eaa9ae1ac89b1c8c8a8104d08c045f78aadb42d/5

**Comment by sanderpick** [comment]
oh yeah, that's cause it's pointing to the mumbai contract, which I think is fine for now
