### ISSUE TITLE
Rig App: Create layout to handle rendering Rig

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#204]

**Comment by joewagner** [comment]
I have an initial app that renders any rig here https://github.com/tablelandnetwork/rigs/tree/joe/animation_url/animation_url
to play with it:
1. clone the rigs repo
2. cd into animation_url
3. npm install && npm run dev
4. open http://localhost:5173?rig=<any valid rig ID>

A potential issue with this is that the rig image urls are all on IPFS and we need to choose a gateway to use within the app.  Currently the app uses `https://ipfs.io/ipfs/`. This works fine, but it is very slow to load initially.  The market places will cache IPFS addresses on there own content server, but I don't know if they are going to do that for each of the sources inside of the animation_url app.  
Is there a better gateway to be using?

**Comment by sanderpick** [comment]
@asutula we can use web3.storage / nft.storage for the images, right? they are pinned to one of those iirc

**Comment by joewagner** [comment]
nre, cross posting.  We have a paid pinning/gateway setup that's working well
