### ISSUE TITLE
Rig App: Create layout to handle rendering multiple Badges

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/rigs#206]

**Comment by joewagner** [comment]
I have an initial app that renders the 6 badges in figma here: https://github.com/tablelandnetwork/rigs/tree/joe/animation_url/animation_url
to play with it:
1. clone the rigs repo
2. cd into animation_url
3. npm install && npm run dev
4. open http://localhost:5173?rig=<any valid rig ID>

If more than 11 badges are shown the layout as it is now will break.  We can accommodate quite a few more than 11, but we need to decide how layout will work and if there is going to be a max number we want to enable?

**Comment by sanderpick** [comment]
how about rows of 5? the we can say max 15 or something
