### ISSUE TITLE
Garage App: Decide on an nft api to use to list nfts that can be used as pilots

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/rigs#217]

**Comment by sanderpick** [comment]
How about https://www.alchemy.com/sdk? I haven't used it, but looks nice.

**Comment by dtbuchholz** [comment]
what about NFTPort? i see them used here and there but haven't tested em out myself https://docs.nftport.xyz/docs/nftport/b3A6MjE0MDYzNzM-retrieve-nf-ts-owned-by-an-account

**Comment by datadanne** [comment]
I like https://docs.zora.co/docs/zora-api, based on the testing I've done in the past they are the best at rendering on chain NFTs. If we don't have a preference my vote is on zora since I've used it in the past :) Plus I think they are free to use right now, we just need to reach out to them and get an api key

**Comment by sanderpick** [comment]
sounds good to me!
