### ISSUE TITLE
Garage App: What IPFS gateway should we use for rig images / should we host rig images ourselves?

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/rigs#218]
I've been using nftstorage in the past for things like the rigs explorer but it is pretty slow and I see gateway timeouts and hit rate limits too often for it to feel useful for production. I've even seen gateway time-outs now while working on the garage using a wallet with just 6 rigs in it so I think it could lead to a pretty bad experience for larger holders. Are there any better alternatives out there that I'm not aware of? Or should we maybe host/cache the images ourselves?

**Comment by joewagner** [comment]
I have the same basic need/question/issue for the animation_url app. https://github.com/tablelandnetwork/rigs/issues/204

**Comment by dtbuchholz** [comment]
If needed, I can run some tests and see if I can quantify the right option -- here are some that come to mind:
- NFT.Storage (which is what PL seems to recommend, though)
- web3.storage
- whatever `ipfs-http-client` uses under the hood (dweb?)
- Piñata
- Filebase
- Cloudflare
- Fleek
- Valist 
- etc. 

The following site is incomplete, but it shows some speed / latency tests; although, the caching is a different story: https://ipnso-com.ipns.dweb.link/

@sanderpick / @asutula -- for the actual Rigs, we made some decisions around the gateway / pinning service. And, I know we had specified NFT.Storage as the right solution based on PL's description. Any opinions or learnings here? Should we pin with multiple providers to help with the potential caching issues noted above?

**Comment by datadanne** [comment]
I don't think pinning with multiple providers would help with caching issues since we have to decide which provider to load from in the client?

Loading the full res images from nft.storage doesn't work well at all, I just did a random test of my rigs and 2/7 timed out. The images are also pretty large at like 2-3Mb, but maybe we can get away with using the thumb images?

**Comment by asutula** [comment]
Or maybe we just pay Pinata for a "dedicated gateway" https://docs.pinata.cloud/rate-limits#dedicated-gateway-rate-limits

**Comment by asutula** [comment]
Oh, looks like that is already included in our paid plan. I just set up a dedicated gateway https://tableland.mypinata.cloud. Give that a try @datadanne .

**Comment by datadanne** [comment]
> Oh, looks like that is already included in our paid plan. I just set up a dedicated gateway https://tableland.mypinata.cloud. Give that a try @datadanne .

Nice! This gateway is much faster for me 👍

**Comment by asutula** [comment]
Cool, closing this.
