### ISSUE TITLE
Rename reputation methods into generic reusable methods

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/rigs#350]
All the functions around garaging, flight status, ft rewards should be written as reusable NFT-reputation and locking out of the market methods. 

E.g., https://github.com/tablelandnetwork/rigs/blob/main/ethereum/contracts/TablelandRigs.sol#L729 pilotRig and parkRig

Those are function names that include branding. We should be building Rigs as highly reusable blueprints and standards for other folks to follow, so I would call those something like: `lockFromTransfer` `unlockFromTransfer`. 

A quick bonus after release would be to extract those methods into `abstract` contracts (e.g., https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/Pausable.sol) that anyone could import into their solidity project and have it just work. this promotes reuse, ease of reuse, and standards. 

Can i get some time with the Rigs Pod to do some rapid renaming in this contract _before_ launch? The reason I think this is urgent and before launch is that some of the state storage needs to be renamed to non-branded keys so that it is actually reusable. 

cc @asutula @sanderpick

**Comment by asutula** [comment]
Sounds like a good idea. I guess the storage keys are the only things that aren't upgradable? If that's the case, we should at least just change those. The rest can come with a contract upgrade and no rush.

**Comment by sanderpick** [comment]
This will be covered in the Token Reputation work
