### ISSUE TITLE
Isolate The Garage as its own contract

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/rigs#355]
The `TablelandRigs.sol` contract is near the 25kb limit, so adding new features will become a problem. If The Garage features become its own contract and are subsequently imported, then this should help reduce the `TablelandRigs.sol` size and also make things more reusable by other projects.

Potentially redundant with ideas noted in https://github.com/tablelandnetwork/rigs/issues/350 around abstract contracts but wanted to flag this, nonetheless.

**Comment by sanderpick** [comment]
dunzo
