### ISSUE TITLE
Rigs Contract: Implement on-chain metadata updates

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/rigs#527]
OpenSea now supports contract-triggered metadata updates: https://twitter.com/ralxzryan/status/1611058555247001601?s=46&t=8DHAlZH_0Qm51OxkZSfXTw

"EIP-4906 is a metadata update extension to ERC-721, with two events `MetadataUpdate` and `BulkMetadataUpdate`, that signal when a token should have its metadata refreshed": https://eips.ethereum.org/EIPS/eip-4906

**Comment by sanderpick** [comment]
i added this one to Garage V2 project.
