### ISSUE TITLE
Publish a new version of @tableland/rigs that uses the v4 sdk

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/rigs#559]
The current version of @tableland/rigs can't be used with @tableland/sdk v4 because of
```
node_modules/@tableland/rigs/deployments.ts(54,5): error TS2322: Type '"polygon-mumbai"' is not assignable to type 'keyof TablelandNetworkConfig'.
```

I also noticed that @tableland/rigs doesn't specify the tableland sdk as a dependency which it probably should?

**Comment by joewagner** [comment]
Do we need to capture the work to update the animation_url?  Or is that part of one of the above draft PRs?

**Comment by asutula** [comment]
There's some discussion happening in Discord about that. Not clear what the path is, but yes, we should capture it as an issue and eventual PR.

**Comment by asutula** [comment]
@joewagner pls ignore my above comment. I mis understood what you were talking about. Yes, we should capture an issue to update the `animation_url` app in this repo.

**Comment by asutula** [comment]
updated this issue with a checklist for the different things that need the sdk update https://github.com/tablelandnetwork/rigs/issues/558
