### ISSUE TITLE
We need a strategy for testnet garage and animation url apps

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/rigs#577]
This includes:
- how/where to deploy testnet versions of the apps
- stable urls for those apps (or not)
- how to write testnet specific values for those apps to the lookups table
- improving more generally the management of tables and their contents within our development workflow

**Comment by sanderpick** [comment]
Is this work still needed? I was gone at the time this issue was created. I was always under the impression that targeting testnet was a local dev thing. ie, no deployments needed.

**Comment by sanderpick** [comment]
Closing for now. We create a diff issue on linear if still needed.
