### ISSUE TITLE
[RIG-21] Need to upgrade the `/ethereum` package to use the latest validator API.

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/rigs#675]
the `/query?s=` endpoint has been deprecated and will stop working soon.  The recommended endpoint is `/api/v1/query?statement=`

<sub>[RIG-21](https://linear.app/tableland/issue/RIG-21/need-to-upgrade-the-ethereum-package-to-use-the-latest-validator-api)</sub>

**Comment by sanderpick** [comment]
@joewagner is this still needed?

**Comment by joewagner** [comment]
Looks like it was fixed by 90a25c1, lets close it
